nome = input("Nome: ")
idade = int(input("Idade: "))
telefone = input("Telefone: ")
email = input("E-mail:")

print("====================================")
print(f"Seu nome é: {nome}")
print(f"Você tem: {idade} anos")
print(f"Telefone de contato: {telefone}")
print(f"E seu e-mail de contato é {email}")
